using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class MktCompanyM
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyShortName { get; set; }
        public string CompanyCode { get; set; }
        public short? LedgerId { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsScrapBuyer { get; set; }
        public bool IsRawMaterialSupplier { get; set; }
        public bool IsOtherSupplier { get; set; }
        public bool IsRepairer { get; set; }
        public bool IsShipper { get; set; }
        public bool IsOutsourceProvider { get; set; }
        public int RoleId { get; set; }
        public short CustomerCategoryId { get; set; }
        public bool IsBillingModeExport { get; set; }
        public byte? BusinessActivityId { get; set; }
        public byte? TypeOfProductId { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public int CompanyCountryId { get; set; }
        public string CompanyCountry { get; set; }
        public int CompanyStateId { get; set; }
        public string CompanyState { get; set; }
        public int CompanyCityId { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyPincode { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyPhoneNoDialingCode { get; set; }
        public string CompanyPhoneNo { get; set; }
        public string CompanyFaxDialingCode { get; set; }
        public string CompanyFaxNo { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public int BillingCountryId { get; set; }
        public string BillingCountry { get; set; }
        public int BillingStateId { get; set; }
        public string BillingState { get; set; }
        public int BillingCityId { get; set; }
        public string BillingCity { get; set; }
        public string BillingPincode { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public int DeliveryCountryId { get; set; }
        public string DeliveryCountry { get; set; }
        public int DeliveryStateId { get; set; }
        public string DeliveryState { get; set; }
        public int DeliveryCityId { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryPincode { get; set; }
        public string TitleOrganizationHead { get; set; }
        public string OrganizationHead { get; set; }
        public string OrganizationHeadDesignation { get; set; }
        public string OrganizationHeadPhoneNoDialingCode { get; set; }
        public string OrganizationHeadPhoneNo { get; set; }
        public string OrganizationHeadEmail { get; set; }
        public string TitleContactPerson { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string ContactPersonPhoneNoDialingCode { get; set; }
        public string ContactPersonPhoneNo { get; set; }
        public string ContactPersonEmail { get; set; }
        public byte CurrencyId { get; set; }
        public string CompanyTinno { get; set; }
        public DateTime? CompanyTindate { get; set; }
        public string CompanyCstno { get; set; }
        public DateTime? CompanyCstdate { get; set; }
        public string CompanyEccno { get; set; }
        public string BankName { get; set; }
        public string AccountNum { get; set; }
        public string RoutingDetails { get; set; }
        public int PaymentTypeId { get; set; }
        public string PortOfDischarge { get; set; }
        public int ExciseTaxId { get; set; }
        public int SalesTaxId { get; set; }
        public bool IsAllowCredit { get; set; }
        public double CreditLimit { get; set; }
        public double AdvanceInPercent { get; set; }
        public double AdvanceInRs { get; set; }
        public int CreditPeriodForFullPayment { get; set; }
        public bool StopNewDelivery { get; set; }
        public bool StopAcceptingOrders { get; set; }
        public bool AlertCustomer { get; set; }
        public bool AlertAccountsTeam { get; set; }
        public string AlertAccountsTeamNums { get; set; }
        public bool PauseProduction { get; set; }
        public double ExcessQuantityPercent { get; set; }
        public double QuantityLimit { get; set; }
        public bool Status { get; set; }
        public double AnnualTargetBusinessVolume { get; set; }
        public bool IsExport { get; set; }
        public bool IsShowJobStatusToCustomer { get; set; }
        public DateTime CreatedDt { get; set; }
        public int CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public int UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public int? DeliveryTypeId { get; set; }
        public string Notes { get; set; }
        public int? ModeOfTransportId { get; set; }
        public int? ShipperDelivery { get; set; }
        public string ShippingMode { get; set; }
        public int? ShippingPeriod { get; set; }
        public double? Cost { get; set; }
        public int? ShipperId { get; set; }
        public int? ShippingPeriodInDays { get; set; }
        public short? ServiceTaxId { get; set; }
        public DateTime? NxtIntDt { get; set; }
        public string NxtWithWhom { get; set; }
        public int NxtEmployee { get; set; }
        public int NxtIntType { get; set; }
        public int NxtReminderId { get; set; }
        public int? DefaultCompanyAddress { get; set; }
        public int? DefaultDeliveryAddress { get; set; }
        public int? DefaultBillingAddress { get; set; }
        public int? DefaultContactPerson { get; set; }
        public int InvoiceTypeId { get; set; }
    }
}
