using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class MtlMaterialM
    {
        public long MaterialId { get; set; }
        public long MaterialSubCategoryId { get; set; }
        public int MaterialCategoryId { get; set; }
        public string MaterialName { get; set; }
        public string VersionNum { get; set; }
        public byte? VersionNumAuto { get; set; }
        public string PartName { get; set; }
        public string MaterialCode { get; set; }
        public string OtherReferenceNo1 { get; set; }
        public string OtherReferenceNo2 { get; set; }
        public bool? IsSoldAsStdProduct { get; set; }
        public bool? IsSoldAsCustomProduct { get; set; }
        public bool? IsSoldAsSpareAccessoryItem { get; set; }
        public bool? IsSoldAsSideScrapItem { get; set; }
        public bool? IsConsumedInProduction { get; set; }
        public bool? IsConsumedInGeneral { get; set; }
        public bool? IsManufacturedInHouse { get; set; }
        public bool? IsPurchaseFromOutsideSuppliers { get; set; }
        public bool? IsReceivedFromProductionAsByproduct { get; set; }
        public bool? IsGeneratedAsScrap { get; set; }
        public bool? IsSellOnlyAgainstPo { get; set; }
        public bool? IsAcceptPoonlyAgainstQuotations { get; set; }
        public bool? IsSellOnlyGoodsWhichLastInspectedDays { get; set; }
        public short? LastInspectDays { get; set; }
        public bool? ShowProductionSeries { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public double? ProposedSaleRate { get; set; }
        public double? DefaultInventoryRate { get; set; }
        public bool? IsAllowDirectPurchaseWithoutPo { get; set; }
        public bool? IsAllowDirectPurchaseWithoutRequest { get; set; }
        public bool? AllowSupplierToQuote { get; set; }
        public string InspectionPolicy { get; set; }
        public double? MaximumRejectionAllowPercentage { get; set; }
        public double MinLeadTime { get; set; }
        public double MinPurOrderQty { get; set; }
        public double MinRate { get; set; }
        public double MaxRate { get; set; }
        public double MinStockQty { get; set; }
        public short? DefaultStorageLocation { get; set; }
        public int? LocationId { get; set; }
        public bool IsExpirable { get; set; }
        public short? DefaultExpiryPeriodDays { get; set; }
        public double? IssueIncrement { get; set; }
        public bool? IsAllowIssueFromSingleBatchOnly { get; set; }
        public bool IsAllowDirectIssue { get; set; }
        public bool IsAllowIssueOnlyTowardsSpecificJob { get; set; }
        public bool? IsAllowTransferToDifferentJobAtWiplevel { get; set; }
        public bool? IsAllowExcessIssueMoreThanJobRequirement { get; set; }
        public double? ExcessAllowanceIssuePercentage { get; set; }
        public double? CurrentRate { get; set; }
        public bool? AllowReValuation { get; set; }
        public short? IssueUnitId { get; set; }
        public bool? IsProductionQtyUnitSameAsSku { get; set; }
        public short? ProductionQtyUnitId { get; set; }
        public bool? IsSetRelationBetweenSkuAndProductionQtyUnit { get; set; }
        public double? CfSkunitIdToProdQtyUnitIdNumerator { get; set; }
        public double? CfSkunitIdToProdQtyUnitIdDenominator { get; set; }
        public double? CfSkunitIdToReportingUnitIdNumerator { get; set; }
        public double? CfSkunitIdToReportingUnitIdDenominator { get; set; }
        public bool? IsOrderAcceptanceUnitSameAsSku { get; set; }
        public short? OrderAcceptanceUnitUnitId { get; set; }
        public bool? IsSetRelationBetweenSkuAndOrderAcceptanceUnit { get; set; }
        public double? CfSkunitIdToPoaunitIdNumerator { get; set; }
        public double? CfSkunitIdToPoaunitIdDenominator { get; set; }
        public bool? IsPurchaseReceiptUnitSameAsSku { get; set; }
        public short? PurchaseReceiptUnitUnitId { get; set; }
        public bool? IsSetRelationBetweenSkuAndPurchaseReceiptUnit { get; set; }
        public double? CfSkunitIdToPurchaseReceiptUnitIdNumerator { get; set; }
        public double? CfSkunitIdToPurchaseReceiptUnitIdDenominator { get; set; }
        public bool? IsSalesDeliveryUnitSameAsSku { get; set; }
        public short? SalesDeliveryUnitUnitId { get; set; }
        public bool? IsSetRelationBetweenSkuAndSalesDeliveryUnit { get; set; }
        public double? CfSkunitIdToSalesDeliveryUnitIdNumerator { get; set; }
        public double? CfSkunitIdToSalesDeliveryUnitUnitIdDenominator { get; set; }
        public int? AcceptableProcessFlowId { get; set; }
        public bool? IsHaveSubAssembly { get; set; }
        public double? ActualStockQty { get; set; }
        public short? CurrencyId { get; set; }
        public bool? IsCompletedSales { get; set; }
        public bool? IsCompletedPurchase { get; set; }
        public bool? IsCompletedStore { get; set; }
        public bool? IsCompletedUnit { get; set; }
        public bool? IsCompletedProcessFlow { get; set; }
        public bool? IsCompletedSubAssembly { get; set; }
        public bool? IsCompletedBom { get; set; }
        public bool? IsCompletedByproduct { get; set; }
        public bool? IsCompletedFiles { get; set; }
        public bool? IsCompletedCharacteristics { get; set; }
        public bool? IsCompletedNotes { get; set; }
        public bool? IsCompletedCharges { get; set; }
        public string Charge1Name { get; set; }
        public string Charge2Name { get; set; }
        public string Charge3Name { get; set; }
        public string Charge4Name { get; set; }
        public short? ErrorMarginPercent { get; set; }
        public long? ParentPartId { get; set; }
        public short? PartTypeId { get; set; }
        public DateTime? CreatedDt { get; set; }
        public short CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public short UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool? IsAllowReceiptWithoutInspectionOld { get; set; }
        public bool? IsAllowSupplierToTransferMaterialToSpecificJobOld { get; set; }
        public short? MainUnitCategoryIdOld { get; set; }
        public double? InitialUsedQtyOld { get; set; }
        public double? InitialAvgPriceInRsOld { get; set; }
        public short? UnitIdOld { get; set; }
        public short? SunitIdOld { get; set; }
        public double? ConversionfactorUnitOld { get; set; }
        public string NotesOld { get; set; }
        public DateTime? ExpiryDtOld { get; set; }
        public bool? IsExpiredOld { get; set; }
        public bool? IsSellToAnyCustomerOld { get; set; }
        public bool? IsPurchaseFromAnySupplierOld { get; set; }
        public short? ParentUnitCategoryIdOld { get; set; }
        public short? MainUnitIdFromOld { get; set; }
        public short? MainUnitIdToOld { get; set; }
        public short? PounitIdOld { get; set; }
        public short? DeliveryUnitIdOld { get; set; }
        public short? PurchaseUnitIdOld { get; set; }
        public short? LaunchUnitIdOld { get; set; }
        public short? MainUnitIdUnitCategoryConversionOld { get; set; }
        public double? ConversionFactorUnitCategoryConversionOld { get; set; }
        public short? ParentUnitIdBasisUnitCategoryConversionOld { get; set; }
        public bool? AllowMigrationToHigherUnitOld { get; set; }
        public bool? AllowMigrationToLowerUnitOld { get; set; }
        public double? InitialStockQtyOld { get; set; }
        public double? InitialAvgPriceOld { get; set; }
        public double? InitialAvgPriceInDefaultCurrencyOld { get; set; }
        public double? TotalReceivedStockQtyOld { get; set; }
        public double? PricePerUnitOld { get; set; }
        public double? AvgPriceOld { get; set; }
        public double? LatestCurrencyPriceOld { get; set; }
        public bool IsService { get; set; }
        public bool? IsQtySensitive { get; set; }
        public bool IsAcceptOnlineOrder { get; set; }
        public bool AcceptOrderFromAll { get; set; }
        public bool AllowExciseCredit { get; set; }
        public double ExciseCreditPercentage { get; set; }
        public bool AllowSalesTaxCredit { get; set; }
        public double SalesCreditPercentage { get; set; }
        public bool IsLocked { get; set; }
        public short Criticality { get; set; }
        public bool InActivePart { get; set; }
        public string DisplayPartName { get; set; }
        public int SetId { get; set; }
        public bool IsCompletedWebsite { get; set; }
        public int DeliveryDays { get; set; }
        public short ItemValue { get; set; }
        public short ItemMovement { get; set; }
    }
}
