using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class MtlSubcategoryM
    {
        public long MaterialSubCategoryId { get; set; }
        public string MaterialSubCategory { get; set; }
        public string MaterialSubCategoryShortName { get; set; }
        public string MaterialSubCategoryCode { get; set; }
        public int MaterialCategoryId { get; set; }
        public int? LedgerId { get; set; }
        public bool? IsSoldAsStdProduct { get; set; }
        public bool? IsSoldAsCustomProduct { get; set; }
        public bool? IsSoldAsSpareAccessoryItem { get; set; }
        public bool? IsSoldAsSideScrapItem { get; set; }
        public bool? IsConsumedInProduction { get; set; }
        public bool? IsConsumedInGeneral { get; set; }
        public bool? IsManufacturedInHouse { get; set; }
        public bool? IsPurchaseFromOutsideSuppliers { get; set; }
        public bool? IsReceivedFromProductionAsByproduct { get; set; }
        public bool? IsGeneratedAsScrap { get; set; }
        public short? MainUnitCategoryId { get; set; }
        public short? IssueUnitId { get; set; }
        public bool? IsRusameAsSku { get; set; }
        public short? RuUnitCategoryId { get; set; }
        public short? RuUnitId { get; set; }
        public bool? IsSetRelation { get; set; }
        public double? CfSkunitIdToReportingUnitIdNumerator { get; set; }
        public double? CfSkunitIdToReportingUnitIdDenominator { get; set; }
        public bool? IsProductionQtyUnitSameAsSku { get; set; }
        public bool? IsOrderAcceptanceUnitSameAsSku { get; set; }
        public bool? IsPurchaseReceiptUnitSameAsSku { get; set; }
        public bool? IsSalesDeliveryUnitSameAsSku { get; set; }
        public double? RejectionMarginProduction { get; set; }
        public int? HighestPriorityProductionDays { get; set; }
        public int? HighPriorityProductionDays { get; set; }
        public int? NormalPriorityProductionDays { get; set; }
        public int? LowPriorityProductionDays { get; set; }
        public int? LowestPriorityProductionDays { get; set; }
        public short? DefaultStorageLocation { get; set; }
        public int? LocationId { get; set; }
        public bool? IsExpirable { get; set; }
        public bool? IsAllowDirectPurchaseWithoutPo { get; set; }
        public bool? IsAllowDirectPurchaseWithoutRequest { get; set; }
        public bool? AllowSupplierToQuote { get; set; }
        public bool? IsDetailsOrderTracking { get; set; }
        public double MinRate { get; set; }
        public double MaxRate { get; set; }
        public string InspectionPolicy { get; set; }
        public double? MaximumRejectionAllowPercentage { get; set; }
        public bool? IsAllowIssueFromSingleBatchOnly { get; set; }
        public bool IsAllowDirectIssue { get; set; }
        public bool IsAllowIssueOnlyTowardsSpecificJob { get; set; }
        public bool? IsAllowTransferToDifferentJobAtWiplevel { get; set; }
        public bool? IsAllowExcessIssueMoreThanJobRequirement { get; set; }
        public double? ExcessIssueAllowancePercentage { get; set; }
        public short? DefaultDeliveryPeriod { get; set; }
        public bool IsCompletedUnit { get; set; }
        public bool IsCompletedCharacteristics { get; set; }
        public bool IsCompletedProdn { get; set; }
        public bool IsCompletedProcesses { get; set; }
        public bool IsCompletedFlow { get; set; }
        public bool IsCompletedRawMtl { get; set; }
        public bool IsCompletedSubAssembly { get; set; }
        public bool IsCompletedByProduct { get; set; }
        public bool IsCompletedStore { get; set; }
        public bool IsCompletedUsage { get; set; }
        public bool IsCompletedBrands { get; set; }
        public bool IsCompletedFiles { get; set; }
        public bool IsCompletedCharges { get; set; }
        public string Charge1Name { get; set; }
        public string Charge2Name { get; set; }
        public string Charge3Name { get; set; }
        public string Charge4Name { get; set; }
        public byte? CurrencyId { get; set; }
        public string TravelerCardFileName { get; set; }
        public short? PartTypeId { get; set; }
        public bool? ShowPartName { get; set; }
        public bool? ShowOtherReferenceNo1 { get; set; }
        public bool? ShowOtherReferenceNo2 { get; set; }
        public bool? ShowMaterialCode { get; set; }
        public double TargetOutputQtyPerDay { get; set; }
        public double TargetOutputQty { get; set; }
        public string TargetOutputUnit { get; set; }
        public double TargetRejectionQtyPerDay { get; set; }
        public double TargetLowProductionQtyPerDay { get; set; }
        public bool? ShowProcesswiseDefaultInventoryRate { get; set; }
        public DateTime CreatedDt { get; set; }
        public short CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public short? UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool? IsAllowReceiptWithoutInspectionOld { get; set; }
        public byte? PrecisionDigitsOld { get; set; }
        public byte? UnitConversionEntryLevelOld { get; set; }
        public bool? IsFixedUnitConversionWithParentUnitOld { get; set; }
        public short? MainUnitIdUnitConversionOld { get; set; }
        public double? ConversionFactorFromMainUnitToParentUnitOld { get; set; }
        public short? ParentUnitIdUnitConversionOld { get; set; }
        public double? ConversionFactorSmuvalueOld { get; set; }
        public double? ConversionFactorRuvalueOld { get; set; }
        public bool IsAllowQuoteRequest { get; set; }
        public int? SalesLedgerId { get; set; }
        public byte? InspectionStylePurchase { get; set; }
        public byte? InspectionStyleStore { get; set; }
        public bool IsService { get; set; }
        public bool IsRequireRawmaterials { get; set; }
        public bool IsRequireSubassemblies { get; set; }
        public bool IsRequireByproducts { get; set; }
        public bool IsRequireFiles { get; set; }
        public bool AskForProductionspeed { get; set; }
        public bool IsAutoSendToFinishGoods { get; set; }
        public byte RejectionOutPutMode { get; set; }
        public int RejectionOutPutMaterialId { get; set; }
        public bool IsRequireLockPart { get; set; }
        public bool Nature { get; set; }
        public short Criticality { get; set; }
        public bool IsAcceptOnlineOrder { get; set; }
        public bool AcceptOrderFromAll { get; set; }
        public bool AllowExciseCredit { get; set; }
        public double ExciseCreditPercentage { get; set; }
        public bool AllowSalesTaxCredit { get; set; }
        public double SalesCreditPercentage { get; set; }
        public bool ExpectFixedChg { get; set; }
        public bool ApplyFixedChg { get; set; }
        public int DeliveryCriteriya { get; set; }
        public bool ShowDisplayPartName { get; set; }
        public bool IsAskPolicyLevelchangeStore { get; set; }
        public bool IsAllowRevaluation { get; set; }
        public bool IsPartSensitiveCriticality { get; set; }
        public bool IsReqProductionSeriesParts { get; set; }
        public bool IsAllowOutsourcedManufacture { get; set; }
        public bool IsCompletedSales { get; set; }
        public short SalesClassificationId { get; set; }
        public short ServiceClassificationId { get; set; }
        public short ExciseClassificationId { get; set; }
    }
}
