using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class PrdWorkOrderProcesses
    {
        public long WorkOrderProcessId { get; set; }
        public long WorkOrderId { get; set; }
        public short ProcessStepId { get; set; }
        public short? WoprocessOrder { get; set; }
        public byte? ComplexityLevelId { get; set; }
        public int? OutputMaterialId { get; set; }
        public bool? IsFinishedProcessOutPut { get; set; }
        public short? ProcessInputUnitId { get; set; }
        public short? ProcessOutputUnitId { get; set; }
        public short? ProcessRejectionUnitId { get; set; }
        public short? WopProductionQtyUnitId { get; set; }
        public short? WopSkunitId { get; set; }
        public bool? IsRelationExistForWopskunitIdToProcessOptunit { get; set; }
        public double? CfWopskunitIdToProcessOptunitIdNumerator { get; set; }
        public double? CfWopskunitIdToProcessOptunitIdDenominator { get; set; }
        public bool? IsProdQtyUnitSameAsSkunit { get; set; }
        public bool? IsRelationExistForSkunitToProdQtyUnit { get; set; }
        public double? CfSkunitIdToProdQtyUnitIdNumerator { get; set; }
        public double? CfSkunitIdToProdQtyUnitIdDenominator { get; set; }
        public short? WopReportingUnitId { get; set; }
        public bool IsRelationExistForProcessOutputUnitToReportingUnit { get; set; }
        public double CfProcessOutputUnitIdToReportingUnitIdNumerator { get; set; }
        public double CfProcessOutPutUnitIdToReportingUnitIdDenominator { get; set; }
        public bool? IsRelationExistForSkunitToReportingUnit { get; set; }
        public double? CfSkunitIdToReportingUnitIdNumerator { get; set; }
        public double? CfSkunitIdToReportingUnitIdDenominator { get; set; }
        public double? ExpProcessOutputQtyNumerator { get; set; }
        public short? ExpProcessOutputQtyUnitIdNumerator { get; set; }
        public double? ExpProcessOutputQtyDenominator { get; set; }
        public short? ExpProcessOutputQtyUnitIdDenominator { get; set; }
        public byte? SetupTimeHours { get; set; }
        public byte? SetupTimeMinutes { get; set; }
        public byte? MinimumTimeHours { get; set; }
        public byte? MinimumTimeMinutes { get; set; }
        public double? QtyProductionUnitVariableTime1 { get; set; }
        public short? ProductionUnitIdVariableTime1 { get; set; }
        public short? ProcessingTimeValueVariableTime1 { get; set; }
        public short? TimeUnitIdVariableTime1 { get; set; }
        public double? OriginalExpProcessOutputQtyInProductionQtyUnit { get; set; }
        public double? OriginalExpProcessOutputQtyInSkunit { get; set; }
        public double? OriginalExpProcessOutputQtyInReportingUnit { get; set; }
        public double? ExpProcessOutputQtyInProductionQtyUnit { get; set; }
        public double? ExpProcessOutputQtyInSkunit { get; set; }
        public double? ExpProcessOutputQtyInReportingUnit { get; set; }
        public double? SuccessQtyInProductionQtyUnit { get; set; }
        public double? SuccessQtyInSkunit { get; set; }
        public double? SuccessQtyInReportingUnit { get; set; }
        public double? SuccessQtyInProcessOptunit { get; set; }
        public double? TrashQtyInProductionQtyUnit { get; set; }
        public double? TrashQtyInSkunit { get; set; }
        public double? TrashQtyInReportingUnit { get; set; }
        public double? TrashQtyInProcessOptunit { get; set; }
        public double? LowProductionQtyInProductionQtyUnit { get; set; }
        public double? LowProductionQtyInSkunit { get; set; }
        public double? LowProductionQtyInReportingUnit { get; set; }
        public double? LowProductionQtyInProcessOptunit { get; set; }
        public double? DoneQtyInProductionQtyUnit { get; set; }
        public double? DoneQtyInSkunit { get; set; }
        public double? DoneQtyInReportingUnit { get; set; }
        public double? DoneQtyInProcessOptunit { get; set; }
        public double? TransferredQtyInProductionQtyUnit { get; set; }
        public double? TransferredQtyInSkunit { get; set; }
        public double? RemainingExpProcessOutputQtyInProductionQtyUnit { get; set; }
        public double? RemainingExpProcessOutputQtyInSkunit { get; set; }
        public double? RemainingExpProcessOutputQtyInReportingUnit { get; set; }
        public double? UnusedProcessOutputQtyInProductionQtyUnit { get; set; }
        public double? UnusedProcessOutputQtyInSkunit { get; set; }
        public double? UsedProcessOutputQtyInProductionQtyUnit { get; set; }
        public double? UsedProcessOutputQtyInSkunit { get; set; }
        public bool? IsOutSource { get; set; }
        public bool? IsOutSourced { get; set; }
        public int ExpProcessTimeMinutes { get; set; }
        public DateTime? ExpArrivalDt { get; set; }
        public DateTime? ExpCloseDt { get; set; }
        public DateTime? PlannedArrivalDt { get; set; }
        public DateTime? PlannedCloseDt { get; set; }
        public DateTime? JobArrivalDt { get; set; }
        public DateTime? LatestJobArrivalDt { get; set; }
        public DateTime? JobStartDt { get; set; }
        public short? JobStartUserId { get; set; }
        public DateTime? LatestJobStartDt { get; set; }
        public short? LatestJobStartUserId { get; set; }
        public DateTime? JobCompleteDt { get; set; }
        public short? JobCompleteUserId { get; set; }
        public bool? IsFirstWop { get; set; }
        public bool? IsStartedWop { get; set; }
        public bool? IsRunningWop { get; set; }
        public bool? IsClosedWop { get; set; }
        public bool IsPaused { get; set; }
        public DateTime? PausedDt { get; set; }
        public DateTime? ResumedDt { get; set; }
        public int PlantId { get; set; }
        public DateTime? ManualStartDt { get; set; }
        public DateTime CreatedDt { get; set; }
        public short CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public short UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public double? TransferredQtyInReportingUnitOld { get; set; }
        public double? UnusedProcessOutputQtyInReportingUnitOld { get; set; }
        public double? UsedProcessOutputQtyInReportingUnitOld { get; set; }
        public double ProcessCost { get; set; }
    }
}
