using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class RightsAstOld
    {
        public int AstrightId { get; set; }
        public int EmployeeTypeId { get; set; }
        public bool GiveAccess { get; set; }
        public string DefaultPage { get; set; }
        public bool FullAccess { get; set; }
        public bool Astcategory { get; set; }
        public bool ViewListOfAstcategory { get; set; }
        public bool CreateAstcategory { get; set; }
        public bool EditAstcategory { get; set; }
        public bool DeleteAstcategory { get; set; }
        public bool AssetType { get; set; }
        public bool ViewListOfAssetType { get; set; }
        public bool CreateAssetType { get; set; }
        public bool EditAssetType { get; set; }
        public bool DeleteAssetType { get; set; }
        public bool Asset { get; set; }
        public bool ViewListOfAsset { get; set; }
        public bool CreateAsset { get; set; }
        public bool EditAsset { get; set; }
        public bool DeleteAsset { get; set; }
        public bool RepairsInAssetDetailEntryPage { get; set; }
        public bool AddRepairTypeInAssetDetailEntryPage { get; set; }
        public bool DeleteRepairTypeInAssetDetailEntryPage { get; set; }
        public bool MaintenanceInAssetDetailEntryPage { get; set; }
        public bool AddMaintenanceTypeInAssetDetailEntryPage { get; set; }
        public bool DeleteMaintenanceTypeInAssetDetailEntryPage { get; set; }
        public bool AssetSupplierEntry { get; set; }
        public bool ViewListOfAssetSuppliers { get; set; }
        public bool ActivateOrDeactivateAssetSupplier { get; set; }
        public bool CreateAssetSupplier { get; set; }
        public bool UpdateAssetSupplierEntry { get; set; }
        public bool CreateOrUpdateLoginForAssetSupplier { get; set; }
        public bool MaintenanceSchedule { get; set; }
        public bool ViewAssetMaintenanceSchedule { get; set; }
        public bool MakeAssetMaintenanceEntry { get; set; }
        public bool ViewProcessMaintenanceSchedule { get; set; }
        public bool MakeProcessMaintenanceEntry { get; set; }
        public bool RepairRequest { get; set; }
        public bool CreateRepairRequest { get; set; }
        public bool ViewListOfRepairRequests { get; set; }
        public bool ApproveOtherRepairRequest { get; set; }
        public bool AutoApproveRepairRequest { get; set; }
        public bool DeleteRepairRequest { get; set; }
        public bool MakeRepairEntryForRequest { get; set; }
        public bool MakeRepairEntryLog { get; set; }
        public bool AssetReports { get; set; }
        public bool ViewStockInventory { get; set; }
        public bool ViewAssetMovement { get; set; }
        public bool ViewMaintenanceStatistics { get; set; }
        public bool ViewOverAllMaintenanceHistory { get; set; }
        public bool ViewRepairStatistics { get; set; }
        public bool ViewRepairHistory { get; set; }
        public bool ViewAssetBudgetReport { get; set; }
        public bool ViewAssetMarketBookValue { get; set; }
        public bool AssetPurchaseOrder { get; set; }
        public bool DefineAssetBudget { get; set; }
        public bool UpdateOrDeleteAssetBudget { get; set; }
        public bool ViewAssetBudgetPlan { get; set; }
        public bool ViewExpiredAssetBudgetPlan { get; set; }
        public bool CreateAssetPo { get; set; }
        public bool AssetPoAutoApprove { get; set; }
        public bool AssetPoapprovaeOtherRequest { get; set; }
        public bool ViewListOfAssetPo { get; set; }
        public bool ApproveOrDisapproveAssetPo { get; set; }
        public bool ReceiveAssetAgainstPo { get; set; }
        public bool AssetMovement { get; set; }
        public bool EnterAssetMovement { get; set; }
        public bool RepairType { get; set; }
        public bool CreateRepairType { get; set; }
        public bool UpdateRepairType { get; set; }
        public bool DeleteRepairType { get; set; }
        public bool MaintenanceType { get; set; }
        public bool CreateMaintenanceType { get; set; }
        public bool UpdateMaintenanceType { get; set; }
        public bool DeleteMaintenanceType { get; set; }
        public bool AssetPlant { get; set; }
        public bool CreateAssetPlant { get; set; }
        public bool UpdateAssetPlant { get; set; }
        public bool DeleteAssetPlant { get; set; }
        public bool AssetArea { get; set; }
        public bool CreateAssetArea { get; set; }
        public bool UpdateAssetArea { get; set; }
        public bool DeleteAssetArea { get; set; }
        public bool AssetLocation { get; set; }
        public bool CreateAssetLocation { get; set; }
        public bool UpdateAssetLocation { get; set; }
        public bool DeleteAssetLocation { get; set; }
        public bool AssetCharacteristics { get; set; }
        public bool CreateAssetCharacteristics { get; set; }
        public bool UpdateAssetCharacteristics { get; set; }
        public bool DeleteAssetCharacteristics { get; set; }
        public bool AssetWarrantyCoverage { get; set; }
        public bool CreateAssetWarranty { get; set; }
        public bool UpdateAssetWarranty { get; set; }
        public bool DeleteAssetWarranty { get; set; }
        public bool AssetInsuranceType { get; set; }
        public bool CreateAssetInsuranceType { get; set; }
        public bool UpdateAssetInsuranceType { get; set; }
        public bool DeleteAssetInsuranceType { get; set; }
        public bool AssetOtherConfiguration { get; set; }
        public DateTime CreatedDt { get; set; }
        public short CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public short UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool AstConfigurationAccess { get; set; }
    }
}
