using System;
using System.Collections.Generic;

namespace EntityLinqMasteringApp.DevERPModels
{
    public partial class RightsMktOld
    {
        public int MktrightsId { get; set; }
        public int EmployeeTypeId { get; set; }
        public bool GiveAccess { get; set; }
        public string DefaultPage { get; set; }
        public bool FullAccess { get; set; }
        public bool CustomerEntry { get; set; }
        public bool ViewListOfCustomers { get; set; }
        public bool ActivateOrDeactivate { get; set; }
        public bool CreateAcustomer { get; set; }
        public bool UpdateCustomerEntry { get; set; }
        public bool ApproveCustomersRegistration { get; set; }
        public bool CreateOrUpdateLoginForCustomer { get; set; }
        public bool RequestForQuote { get; set; }
        public bool EnterRequestForQuote { get; set; }
        public bool ViewRequestForQuote { get; set; }
        public bool Quotations { get; set; }
        public bool CreateQuotation { get; set; }
        public bool ViewQuotation { get; set; }
        public bool? AllowQuotationBelowRecommended { get; set; }
        public bool ApproveQuotation { get; set; }
        public bool PurchaseOrders { get; set; }
        public bool EnterPurchaseOrder { get; set; }
        public bool FinalizePurchaseOrder { get; set; }
        public bool RejectPurchaseOrder { get; set; }
        public bool DeletePurchaseOrder { get; set; }
        public bool? RejectFinalizedPurchaseOrder { get; set; }
        public bool ViewAndPrintPoandPi { get; set; }
        public bool ApprovePo { get; set; }
        public bool RejectPo { get; set; }
        public bool ShipperEntry { get; set; }
        public bool ViewListOfShippers { get; set; }
        public bool ActivateOrDeactivateShipper { get; set; }
        public bool CreateShipper { get; set; }
        public bool UpdateShipperEntry { get; set; }
        public bool CreateOrUpdateLoginForShipper { get; set; }
        public bool DeliveryRecord { get; set; }
        public bool CreateLocalDeliveryRecord { get; set; }
        public bool CreateExportDeliveryRecord { get; set; }
        public bool CreateScrapDeliveryRecord { get; set; }
        public bool CreateDeliveryRecordForRejectedMtls { get; set; }
        public bool DeliveryRecordWithOutPoreference { get; set; }
        public bool DeliveryRecordWithOutPackingList { get; set; }
        public bool MarkCompletePoitemMoreThanExcessQtyLimitInDeliveryRecord { get; set; }
        public bool MarkCompletePoitemLessThanDeficientQtyLimitInDeliveryRecord { get; set; }
        public bool ViewListOfOnWayDeliveryRecords { get; set; }
        public bool ViewListOfDeliveredDeliveryRecords { get; set; }
        public bool AddReceivedDateForDeliveryRecord { get; set; }
        public bool AddTrackingNoForDeliveryRecord { get; set; }
        public bool Invoice { get; set; }
        public bool CreateLocalInvoice { get; set; }
        public bool CreateExportInvoice { get; set; }
        public bool CreateScrapInvoice { get; set; }
        public bool InvoiceAgainstDeliveryRecord { get; set; }
        public bool InvoiceWithPoreference { get; set; }
        public bool InvoiceWithOutPoreference { get; set; }
        public bool InvoiceWithOutPackingList { get; set; }
        public bool MakeChangeInPoitemRateInInvoice { get; set; }
        public bool MakeChangeInOrderQtyInInvoice { get; set; }
        public bool MarkCompletePoitemMoreThanExcessQtyLimitInInvoice { get; set; }
        public bool MarkCompletePoitemLessThanDeficientQtyLimitInInvoice { get; set; }
        public bool MakeDiscountInInvoice { get; set; }
        public bool MakePaymentReceiveInInvoice { get; set; }
        public bool FullPaymentReceiveInInvoice { get; set; }
        public bool PartialPaymentReceiveInInvoice { get; set; }
        public bool AdvancePaymentReceiveInInvoice { get; set; }
        public bool ViewListOfInvoices { get; set; }
        public bool FullyPaidInvoices { get; set; }
        public bool PartiallyPaidInvoices { get; set; }
        public bool UnPaidInvoices { get; set; }
        public bool AddTrackingNoForInvoiceList { get; set; }
        public bool Feedback { get; set; }
        public bool ViewFeedbackAnalysis { get; set; }
        public bool EnterFeedback { get; set; }
        public bool TaxStructure { get; set; }
        public bool CreateTaxStructure { get; set; }
        public bool ViewListOfTaxStructures { get; set; }
        public bool EditTaxStructure { get; set; }
        public bool DeleteTaxStructure { get; set; }
        public bool ReceivePayment { get; set; }
        public bool ReceivePaymentFromNewFund { get; set; }
        public bool ReceivePaymentFromAdvance { get; set; }
        public bool SendPayment { get; set; }
        public bool SendPaymentForAdvance { get; set; }
        public bool SendPaymentAgainstMaterialFromNewFund { get; set; }
        public bool SendPaymentAgainstMaterialFromAdvance { get; set; }
        public bool Communication { get; set; }
        public bool CreateCommunicationEntry { get; set; }
        public bool ViewCommunication { get; set; }
        public bool CustomerCategory { get; set; }
        public bool ViewListOfCustomerCategory { get; set; }
        public bool CreateCustomerCategory { get; set; }
        public bool EditCustomerCategory { get; set; }
        public bool DeleteCustomerCategory { get; set; }
        public bool TermsAndConditions { get; set; }
        public bool ViewListOfTerms { get; set; }
        public bool CreateTermCategory { get; set; }
        public bool CreateTerm { get; set; }
        public bool DeleteTerms { get; set; }
        public bool Currency { get; set; }
        public bool ViewListOfCurrency { get; set; }
        public bool CreateCurrency { get; set; }
        public bool EditCurrency { get; set; }
        public bool DeleteCurrency { get; set; }
        public bool OtherConfiguration { get; set; }
        public bool MktOtherConfiguration { get; set; }
        public bool SalesOtherConfiguration { get; set; }
        public bool Reports { get; set; }
        public bool ViewPendingDispatches { get; set; }
        public bool ViewCustomerAnalysis { get; set; }
        public bool ViewCompanyInteraction { get; set; }
        public bool ViewPurchaseOrderStatus { get; set; }
        public DateTime CreatedDt { get; set; }
        public short CreatedUserId { get; set; }
        public DateTime UpdatedDt { get; set; }
        public short UpdatedUserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool MktReports { get; set; }
        public bool ViewMktCustomerLoyalty { get; set; }
        public bool ViewMktInquiryLog { get; set; }
        public bool ViewMktInquiryResponse { get; set; }
        public bool ViewMktQuotationHistory { get; set; }
        public bool ViewMktQuoteLog { get; set; }
        public bool ViewMktSalesLog { get; set; }
        public bool ViewMktInvoiceHistory { get; set; }
        public bool ViewMktCustomerwiseSalesSummary { get; set; }
        public bool ViewMktProductwiseSalesSummary { get; set; }
        public bool ViewMktReceivables { get; set; }
        public bool ViewMktPaymentReceiptHistory { get; set; }
        public bool MktConfigurationAccess { get; set; }
    }
}
